//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Book_Transaction = new HashSet<Book_Transaction>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public Nullable<int> BookAuthorId { get; set; }
        public Nullable<int> BookPublisherId { get; set; }
        public Nullable<int> BookPrice { get; set; }
        public string BookCatagory { get; set; }
        public Nullable<int> NoofCopies { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Transaction> Book_Transaction { get; set; }
    }
}
