//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<System.DateTime> BookIssueDate { get; set; }
        public Nullable<System.DateTime> BookSubmitDate { get; set; }
        public string TransactionStatus { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
